name: Aktualizacja Danych Adresowych

on:
  schedule:
    # Uruchamia się automatycznie 1-go dnia każdego miesiąca o 02:00 UTC
    - cron: '0 2 1 * *'
  workflow_dispatch: # Pozwala na ręczne uruchomienie akcji z poziomu strony GitHuba

jobs:
  update-csv:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wymagane do wysłania zmian (push) do repozytorium

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Tippecanoe
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libsqlite3-dev zlib1g-dev
          git clone https://github.com/felt/tippecanoe.git
          cd tippecanoe
          make -j$(nproc)
          sudo make install

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalacja zależności Python
        run: |
          python -m pip install --upgrade pip
          pip install osmium

      - name: Pobranie i aktualizacja danych
        run: python fetch_addresses.py

      - name: Zapisanie zmian w repozytorium (Commit & Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Dodajemy wszystkie pliki csv oraz pmtiles z folderu addresses/pl/
          git add addresses/pl/*.csv
          git add addresses/pl/*.pmtiles
          
          # Commit wykona się tylko, jeśli są jakieś zmiany w plikach
          git commit -m "Automatyczna aktualizacja danych adresowych (CSV + PMTiles)" || exit 0
          
          # Wysłanie zmian do repozytorium
          git push
